/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./web/templates/**/*.templ",
    "./web/templates/**/*_templ.go",
    "./web/src/ts/**/*.ts",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#00E5A0",
        "on-background": "#e5e2e1",
        "surface-container-highest": "#353534",
        "secondary-container": "#00C9FF",
        "on-surface": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "surface-tint": "#b8c3ff",
        "on-primary-container": "#efefff",
        "tertiary-container": "#d0a600",
        "error": "#FC466B",
        "tertiary-fixed": "#ffe08b",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#00E5A0",
        "primary-fixed-dim": "#b8c3ff",
        "surface-container-lowest": "#0e0e0e",
        "secondary": "#00E5A0",
        "on-tertiary-container": "#4f3d00",
        "on-primary": "#002388",
        "on-tertiary-fixed": "#241a00",
        "on-surface-variant": "#c4c5d9",
        "on-secondary-fixed": "#002107",
        "outline-variant": "#434656",
        "surface-variant": "#353534",
        "on-tertiary": "#3d2f00",
        "tertiary-fixed-dim": "#f1c100",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed-variant": "#00531c",
        "inverse-primary": "#124af0",
        "inverse-on-surface": "#313030",
        "tertiary": "#f1c100",
        "on-primary-fixed": "#001356",
        "primary": "#b8c3ff",
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1c1b1b",
        "primary-container": "#2e5bff",
        "background": "#131313",
        "surface-bright": "#393939",
        "outline": "#8e90a2",
        "on-secondary-container": "#003a11",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#0035be",
        "surface": "#131313",
        "surface-container": "#201f1f",
        "on-secondary": "#003911",
        "on-tertiary-fixed-variant": "#584400",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
